export const categories = [
  "Food",
  "Travel",
  "Entertainment",
  "Shopping",
  "Health",
  "Business",
  "Income",
  "Utilities",
  "Savings",
];

export const transactions = [
  {
    id: "exp_01",
    title: "Coffee with client",
    category: "Food",
    amount: 14.5,
    date: "2026-06-18",
    notes: "Meeting at downtown cafe",
    type: "expense",
  },
  {
    id: "exp_02",
    title: "Project payout",
    category: "Income",
    amount: 850.0,
    date: "2026-06-17",
    notes: "Consulting fee",
    type: "income",
  },
  {
    id: "exp_03",
    title: "Gym membership",
    category: "Health",
    amount: 45.0,
    date: "2026-06-16",
    notes: "Monthly subscription",
    type: "expense",
  },
  {
    id: "exp_04",
    title: "Design software",
    category: "Business",
    amount: 99.99,
    date: "2026-06-14",
    notes: "Annual license",
    type: "expense",
  },
  {
    id: "exp_05",
    title: "Mobile top-up",
    category: "Utilities",
    amount: 25.0,
    date: "2026-06-13",
    notes: "Data plan renewal",
    type: "expense",
  },
];
